blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/J3WvbBUU8Z
    about: Join our Discord server for support and updates.
  - name: Telegram group
    url: https://t.me/echo_extension
    about: Join our Telegram discussion group for support and updates.